def draw_diamond():
    print("    /\\")
    print("   /  \\")
    print("  /    \\")
    print(" /      \\")
    print("/        \\")
    print("\\        /")
    print(" \\      /")
    print("  \\    /")
    print("   \\  /")
    print("    \\/")


def draw_x():
    print("\\        /")
    print(" \\      /")
    print("  \\    /")
    print("   \\  /")
    print("    \\/")
    print("    /\\")
    print("   /  \\")
    print("  /    \\")
    print(" /      \\")
    print("/        \\")

def draw_rocket():
    print("    /\\")
    print("   /  \\")
    print("  /    \\")
    print(" /      \\")
    print("/        \\")
    print("+--------+")
    print("|        |")
    print("|        |")
    print("+--------+")
    print("| United |")
    print("| States |")
    print("+--------+")
    print("|        |")
    print("|        |")
    print("+--------+")
    print("    /\\")
    print("   /  \\")
    print("  /    \\")
    print(" /      \\")
    print("/        \\")

draw_diamond()
draw_x()
draw_rocket()